name: PR Follows Template

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions:
  pull-requests: read
  issues: read
  contents: read

jobs:
  template-check:
    runs-on: ubuntu-latest

    steps:
      - name: Get PR Number
        id: pr
        run: |
          echo "number=${{ github.event.pull_request.number }}" >> "$GITHUB_OUTPUT"

      - name: Enforce Template
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = Numer('${{ steps.pr.outputs.number }}');
            const script = require('./pr-template.js');
            await script({github, context, core, prNumber})
