name: Update issue template versions
on:
    release:
        types: [ published, edited, deleted ]
    workflow_dispatch:

permissions:
    contents: write
    pull-requests: write

jobs:
    sync-versions:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Install js-yaml
              run: npm install js-yaml

            - name: Update Issue Template
              id: sync_script
              uses: actions/github-script@v8
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      const script = require('./.github/scripts/sync-versions.js');
                      await script({ github, context, core });

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v8
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: "chore: update sonolink_version dropdown [skip ci]"
                  title: "chore: add ${{ steps.sync_script.outputs.version_tags }} to sonolink_version dropdown"
                  body: "Automated update of bug report version dropdown based on latest releases."
                  branch: chore/sync-template-versions
                  base: main
                  delete-branch: true
